# LU Decomposition

In [2]:
import numpy as np
from scipy import linalg

In [ ]:
a = np.array([[3,1,1], [1,2,1],[0,-1,1]])
b = np.array([1,2,3])

In [8]:
lu, p = linalg.lu_factor(a)

In [9]:
linalg.lu_solve((lu, p), b)

array([-0.57142857, -0.14285714,  2.85714286])

In [31]:
print("L x U")
print(lu)

print("\nP")
print(type(p))
print(p)
print("\n Why is it a vector?")

L x U
[[ 3.          1.          1.        ]
 [ 0.33333333  1.66666667  0.66666667]
 [ 0.         -0.6         1.4       ]]

P
<class 'numpy.ndarray'>
[0 1 2]

 Why is it a vector?



# Inverse Matrix

In [32]:
a1 = np.array([[3,1,1], [1,2,1],[0,-1,1]])
np.linalg.inv(a1)

array([[ 0.42857143, -0.28571429, -0.14285714],
       [-0.14285714,  0.42857143, -0.28571429],
       [-0.14285714,  0.42857143,  0.71428571]])

# Solving Equations

In [34]:
c = np.array([[3,1,1], [1,2,1],[0,-1,1]])
d= np.array([1,2,3])

In [40]:
sol = np.linalg.solve(c,d)
print(sol)

[-0.57142857 -0.14285714  2.85714286]


In [43]:
print("Check the answer")
sol2 = np.dot(np.linalg.inv(c), d)
print (sol2)

Check the answer
[-0.57142857 -0.14285714  2.85714286]
